### ISSUE TITLE
Update Dockerfile and README for Vue + Tailwind build process

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#490]
Title: Update Dockerfile and README for Vue + Tailwind Build Process

### Description
We need to update our Dockerfile and README to reflect the new instructions required for developing and deploying our project with the Vue + Tailwind build process. This will ensure that all team members and future contributors have the correct information for setting up the development environment and deploying to production.

### TODO
- [ ] Update Dockerfile for development environment
- [ ] Update Dockerfile for production environment
- [ ] Revise README with new setup instructions
- [ ] Add section in README about Vue + Tailwind build process
- [ ] Update any other relevant documentation

### Technical Considerations
- Consider separating development and production Dockerfiles
- Ensure all necessary dependencies for Vue and Tailwind are included
- Optimize the production build process for smaller image size and faster builds
- Include instructions for running and building the project both with and without Docker

<details>
<summary>Detailed Changes</summary>

#### Dockerfile Updates
- Add Node.js and npm installation steps
- Include Vue CLI and Tailwind CSS installation
- Set up proper build commands for Vue + Tailwind
- Optimize production image by using multi-stage builds

#### README Updates
- Add section on "Development with Vue + Tailwind"
- Include instructions for installing dependencies
- Explain how to run the development server
- Describe the build process for production
- Update any existing sections that may be affected by the new build process

</details>

---

<details>
<summary>.prompt file for this ticket description</summary>

```prompt
# The body of a .prompt file also supports any context provider
# that you have added to your config by referencing the name of
# the context provider. NOTE: the use of curly braces instead of
# the `@` symbol.
#
#   e.g. `{{{url "https://github.com/continuedev/continue"}}}`
#
# Available context providers:
#   - {{ url }}
#   - {{ file }}
#   - {{ clipboard }}
#
# Available variables:
#   - {{{ input }}}
#   - {{{ currentFile }}}
#
# To learn more, see the full .prompt file reference:
# https://docs.continue.dev/walkthroughs/prompt-files
#
temperature: 0.5
maxTokens: 2048
---

<system>
You are an expert programmer and humble contributor to the open-source community.
</system>

Write a brief github ticket title and description based on: `{{{input}}}`. 
If it seems relevant, use the content of {{{currentFile}}} to inform the ticket (again but only if it seems relevant). 

Be sure to include the following:
1. A clear and concise title
2. A detailed description of the issue or feature
3. TODO checkboxes for task items
4. ONE OF: Acceptance criteria, Technical considerations OR Potential Pitfalls.
5. Use `###` for headers.
6. Include longform content within a `<details><summary` toggle using github markdown syntax.
```
