### ISSUE TITLE
Update API Routes: Separate v1 and v2 and Update Mounting in config.ru

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#501]
Description:
We need to refactor our API routes by separating v1 and v2 into distinct files and updating the mounting process in config.ru. This will improve code organization, maintainability, and make it easier to manage different API versions.

### Tasks:
- [x] Create separate route files for v1 and v2 APIs (v1.rb and v2.rb)
- [x] Move existing v1 routes to v1.rb
- [x] Move existing v2 routes to v2.rb
- [x] Update config.ru to mount v1 and v2 routes individually
- [x] Ensure all existing API endpoints continue to function correctly after the refactor

### Technical Considerations:
- The current API structure combines v1 and v2 routes in a single file, which may lead to confusion and difficulties in maintaining separate versions.
- Separating the routes will allow for better version control and easier implementation of future API versions.
- Updating config.ru to mount v1 and v2 separately will provide more flexibility in handling different API versions.

<details>
<summary>Current API Routes Structure</summary>

```
## API v1
GET    /v1/status                               Onetime::App::API#status
POST   /v1/share                                Onetime::App::API#share
POST   /v1/generate                             Onetime::App::API#generate
POST   /v1/create                               Onetime::App::API#create
POST   /v1/secret/:key                          Onetime::App::API#show_secret
GET    /v1/private/recent                       Onetime::App::API#show_metadata_recent
GET    /v1/metadata/recent                      Onetime::App::API#show_metadata_recent
GET    /v1/private/:key                         Onetime::App::API#show_metadata
POST   /v1/private/:key                         Onetime::App::API#show_metadata
GET    /v1/metadata/:key                        Onetime::App::API#show_metadata
POST   /v1/metadata/:key                        Onetime::App::API#show_metadata
POST   /v1/private/:key/burn                    Onetime::App::API#burn_secret
POST   /v1/account/destroy                      Onetime::App#destroy_account

## API v2
GET    /v2/status                                Onetime::App::APIV2#status
GET    /v2/version                               Onetime::App::APIV2#version
```
</details>

This refactoring will set the groundwork for better API version management and make it easier to maintain and extend our API in the future.
