### ISSUE TITLE
Fix ArgumentError in Session.generate_id method

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#506]
An ArgumentError is occurring in the `Session.generate_id` method due to a mismatch in the number of arguments. This issue was introduced in PR #505 when merging changes from v0.15.0 into v0.16.0. The error suggests that the method is being called with 3 arguments, but it expects 0.

### TODO
- [ ] Update the calling code to use the correct method signature 
- [ ] Test the fix to ensure it resolves the ArgumentError
- [ ] Update any calling code that may be affected by this change

### Technical Considerations
<details>
<summary>Click to expand</summary>

The `generate_id` method in the `Onetime::Session` class is currently defined as:

```ruby
def self.generate_id
  input = SecureRandom.hex(32)
  Digest::SHA256.hexdigest(input).to_i(16).to_s(36)
end
```

</details>

### Potential Pitfalls
- Changing the `generate_id` method signature may affect other parts of the codebase that rely on its current implementation.
- Ensure that the fix doesn't introduce any security vulnerabilities, especially since this method is used for generating session IDs.
