### ISSUE TITLE
Rename `bin/ots irb` command to `console`

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#509]
Description:
We need to rename the `bin/ots irb` file to `bin/ots console` and update the `lib/onetime/irb.rb` file accordingly. This change will align our project structure with common Ruby conventions and improve clarity for developers.

### Tasks:
- [x] Rename `bin/ots` command
- [x] Update `lib/onetime/irb.rb` to reflect the new file name
- [x] Update any documentation or references to `bin/ots` throughout the project
- [ ] Test the new `bin/console` to ensure it works as expected

### Technical Considerations:
- Ensure that the `Onetime.boot!` call in `irb.rb` still works correctly after the rename
- Check if any other files or scripts depend on the `bin/ots` name and update them accordingly
- Consider updating the `Gemfile` to reflect any changes in dependencies related to this rename

<details>
<summary>Additional Context</summary>

The current `lib/onetime/irb.rb` file contains:

```ruby
require 'onetime'

Onetime.info 'Calling Onetime.boot!...'
Onetime.boot! :cli
```

We should ensure that this functionality remains intact after the rename, and consider if any adjustments are needed to support the new `bin/console` name.

</details>

**Comment by delano** [comment]
```ruby
# Customize the prompt
if defined?(IRB)
  require "irb/completion"
  IRB.conf[:PROMPT][:ONETIME] = {
    :PROMPT_I => "onetime> ",    # The main prompt
    :PROMPT_S => "onetime%l ",   # The prompt for continuing strings
    :PROMPT_C => "onetime* ",    # The prompt for continuing statements
    :PROMPT_N => "onetime> ",    # The prompt for nested statements
    :RETURN => "=> %s\n"         # The format for return values
  }
  #IRB.CurrentContext.prompt_mode = :CUSTOM1
  IRB.conf[:PROMPT_MODE] = :ONETIME

  # Try to set it for the current context, if it exists
  if defined?(IRB.CurrentContext) && IRB.CurrentContext
    IRB.CurrentContext.prompt_mode = :ONETIME
  end
end

```
