### ISSUE TITLE
Implement dual-build config for local and prod environments

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#522]
Title: Implement dual-build configuration for local and production environments

Description:
We need to set up a dual-build configuration to address the need for both pre-built assets with consistent names for local development and content-hashed filenames for production builds. This will improve our development workflow and enable proper cache busting in production.

### Tasks:
- [x] Create two Vite config files: `vite.config.ts` and `vite.config.local.ts`
- [x] Update `package.json` with separate build scripts for local and production
- [x] Configure `vite.config.ts` for production builds with content hashing
- [x] Configure `vite.config.local.ts` for local builds without content hashing
- [ ] Modify `.gitignore` to include local build output
- [x] Update build script to output local builds to a different directory
- [x] Update documentation for developers on using the new build process

### Technical considerations:
- Ensure that the local build output directory (`dist-local`) is properly tracked in version control
- Consider the impact on CI/CD pipelines and adjust accordingly
- Evaluate the need for additional npm scripts to streamline the development process

<details>
<summary>Detailed Configuration</summary>

```typescript
// vite.config.local.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  build: {
    outDir: 'dist-local',
    rollupOptions: {
      output: {
        entryFileNames: `assets/[name].js`,
        chunkFileNames: `assets/[name].js`,
        assetFileNames: `assets/[name].[ext]`
      }
    }
  }
})
```

```json
// package.json
{
  "scripts": {
    "build": "vite build",
    "build:local": "vite build --config vite.config.local.ts"
  }
}
```

```gitignore
# .gitignore
/dist
!/dist-local
```
</details>
