### ISSUE TITLE
Email verification loop: users unable to login after signup

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#526]
Title: Email Verification Loop: Users Unable to Log In After Signup

### Description
Users are experiencing a login issue after signing up. Upon registration, they receive a message stating "A verification was sent to xxx," but the verification email is not received. Interestingly, the "Forgot Password" feature successfully sends an email to the same address, allowing users to reset their password. However, attempting to log in after resetting the password results in the same verification message, creating a loop that prevents access to the account.

### TODO
- [ ] Investigate why verification emails are not being sent during signup
- [ ] Check if verification emails are being marked as sent in the system
- [ ] Verify email sending configuration for different types of emails (verification vs. password reset)
- [ ] Implement a solution to break the verification loop after password reset

### Technical Considerations
1. Email sending configuration: The issue may be related to the email configuration in the application. The fact that password reset emails are sent successfully suggests that the email service is working for some types of emails but not for verification emails.

2. User verification status: There might be an issue with how the user's verification status is being tracked or updated in the database.

3. Authentication flow: The authentication process may need adjustment to handle cases where a user has reset their password but hasn't completed email verification.

<details>
<summary>Relevant Configuration</summary>

```yaml
:authentication:
  :enabled: true
  :signup: true
  :signin: true
  :autoverify: false

:emailer:
  :mode: <%= ENV['EMAILER_MODE'] || :smtp %>
  :from: <%= ENV['FROM'] || 'CHANGEME@example.com' %>
  :fromname: <%= ENV['FROMNAME'] || 'Jan' %>
  :host: <%= ENV['SMTP_HOST'] || 'localhost' %>
  :port: <%= ENV['SMTP_PORT'] || 587 %>
  :user: <%= ENV['SMTP_USERNAME'] || 'CHANGEME' %>
  :pass: <%= ENV['SMTP_PASSWORD'] || 'CHANGEME' %>
  :tls: <%= ENV['SMTP_TLS'] || true %>
```

This configuration shows that email verification is required (:autoverify: false) and provides details on the email sending setup.
</details>

**Comment by syndimann** [comment]
Hey @delano i registered via onetimesecret.com as well as in a locally envorinment and wanted to use the account to use the ots-api rest-enpoints but i think i am affected by this bug, so i got the email from onetimesecret.com with the ots link that i opened, but everytime i try to login it, the screen states that a verification mail has been sent but it seems to i am not logged in and that the account is not verified yet. is there any way to circumvent this?

**Comment by delano** [comment]
Hmm, there must be an issue where accounts aren't being verified even after clicking the link. I'll need to look into that separately b/c yeah, that's not very user friendly!

For now, for onetimesecret.com I can manually verify -- just send me an email with the account to support@ (onetimesecret.com). For your local instance, it's a bit annoying but you can manually verify by updating the customer record in redis. See my comment here: https://github.com/onetimesecret/onetimesecret/issues/484#issuecomment-2239803262

**Comment by syndimann** [comment]
Thanks a lot @delano that helped me a lot, i was able to set up my local environment!
