### ISSUE TITLE
Custom Font Not Loading in Safari, Works in Chrome

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#598]
### Description

Our custom font (Zilla Slab) is not loading correctly in Safari browsers, while it appears to work as expected in Chrome. This inconsistency affects the visual presentation of our web application and needs to be addressed to ensure a uniform user experience across different browsers.

### TODO

- [ ] Verify font file paths in the Tailwind configuration
- [ ] Check for any Safari-specific font loading issues
- [ ] Test different font-display values
- [ ] Investigate potential CORS issues
- [ ] Review Content Security Policy settings

### Technical Considerations

1. Safari has stricter rules for font loading, especially regarding cross-origin requests.
2. The `font-display` property might need adjustment for better performance in Safari.
3. The Tailwind configuration method for loading fonts might be affecting Safari differently than Chrome.

<details>
<summary>Relevant Configuration</summary>

```typescript
function({ addBase, theme }) {
  addBase({
    '@font-face': [
      {
        fontFamily: 'Zilla Slab',
        fontWeight: '400',
        fontStyle: 'normal',
        fontDisplay: 'swap',
        src: 'url("/fonts/zs/ZillaSlab-Regular.woff2") format("woff2")',
      },
      {
        fontFamily: 'Zilla Slab',
        fontWeight: '700',
        fontStyle: 'normal',
        fontDisplay: 'swap',
        src: 'url("/fonts/zs/ZillaSlab-Bold.woff2") format("woff2")',
      },
    ],
  })
},
```
</details>

### Potential Pitfalls

1. Incorrect file paths or missing font files in the server directory structure.
2. CORS issues if fonts are hosted on a different domain.
3. Content Security Policy blocking font loading in Safari.
4. Differences in how Tailwind and traditional CSS handle font loading across browsers.

### Screenhots

![Screenshot 2024-09-03 at 12 31 16](https://github.com/user-attachments/assets/39ebbf8b-0d03-40cb-a59a-3efa7491e6ed)
![Screenshot 2024-09-03 at 12 32 03](https://github.com/user-attachments/assets/3a83b03b-ef93-4c91-aede-1a3e0f1d66f2)
