### ISSUE TITLE
Evaluate Falcon Web Server for v0.18 release

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#622]
### Description

We need to research and evaluate the Falcon web server as a potential solution for Rack 3 and Ruby 3 feature support in both development and production environments. This investigation will help us determine if Falcon is a suitable alternative to our current web server setup.

### TODO

- [x] Research Falcon web server's features and capabilities
- [x] Assess Falcon's compatibility with Rack 3
- [x] Evaluate Falcon's support for Ruby 3 features
- [x] Compare Falcon's performance to our current web server in development and production
- [x] Document findings and recommendations

### Technical Considerations

- Rack 3 compatibility: Ensure Falcon fully supports Rack 3 specifications
- Ruby 3 support: Verify Falcon works seamlessly with Ruby 3 features and optimizations
- Performance metrics: Compare request handling, concurrency, and memory usage
- Configuration options: Evaluate ease of setup and customization for different environments
- Integration with existing tools: Assess compatibility with our current deployment pipeline and monitoring solutions

<details>
<summary>Additional Resources</summary>

- Falcon GitHub repository: https://github.com/socketry/falcon
- Rack 3 documentation: https://github.com/rack/rack/blob/main/SPEC.rdoc
- Ruby 3 release notes: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
</details>

**Comment by delano** [comment]
### [Falcon migration guide.md](https://github.com/user-attachments/files/16922957/Falcon.migration.guide.md)

# Comprehensive Guide: Migrating from Thin to Falcon

## 1. Gemfile Updates

```ruby
# Before
gem 'thin'

# After
gem 'falcon'
gem 'async'
gem 'async-http'
```

Run `bundle install` after updating.

## 2. Server Configuration

### Thin (before):
```ruby
# config.ru
require './app'
run Rack::URLMap.new('/' => App.new)

# thin.yml
---
address: 0.0.0.0
port: 3000
timeout: 30
max_conns: 1024
max_persistent_conns: 512
environment: production
servers: 4
```

### Falcon (after):
```ruby
# config.ru
require './app'
run App.new

# falcon.rb
#!/usr/bin/env -S falcon host
require 'async/http/internet'

Falcon.load_app do |app, options|
  options[:bind] = 'http://0.0.0.0:3000'
  options[:count] = 4  # Similar to Thin's 'servers'
  options[:timeout] = 30
  options[:reuse_port] = true
end
```

## 3. Start Commands

### Thin:
```bash
thin start -C thin.yml
```

### Falcon:
```bash
falcon host
```

## 4. Event Loop and Concurrency Model

### Thin (EventMachine):
```ruby
EM.run do
  EM.add_periodic_timer(5) { puts "I'm alive" }
end
```

### Falcon (async):
```ruby
require 'async'

Async do |task|
  task.sleep(5)
  puts "I'm alive"
  task.yield
end
```

## 5. WebSocket Handling

### Thin:
```ruby
EM::WebSocket.run(host: '0.0.0.0', port: 8080) do |ws|
  ws.onopen { |handshake| puts "WebSocket connection open" }
  ws.onclose { puts "Connection closed" }
  ws.onmessage { |msg| ws.send "Received: #{msg}" }
end
```

### Falcon:
```ruby
require 'async/websocket/adapters/rack'

class WebSocketApp
  def call(env)
    Async::WebSocket::Adapters::Rack.open(env) do |connection|
      while message = connection.read
        connection.write(message)
        connection.flush
      end
    end
    
    [200, {}, []]
  end
end

run WebSocketApp.new
```

## 6. Database Connections

Ensure your database adapter is async-compatible. For PostgreSQL:

```ruby
# Gemfile
gem 'sequel'
gem 'sequel_pg'
gem 'pg'

# Database connection
require 'sequel'
DB = Sequel.connect('postgres://user:password@localhost/database', max_connections: 10)
```

## 7. Background Jobs

If using Sidekiq, no major changes needed. For custom job processing:

```ruby
# Before (Thin/EventMachine)
EM.add_periodic_timer(60) { process_jobs }

# After (Falcon/async)
Async do |task|
  loop do
    process_jobs
    task.sleep(60)
  end
end
```

## 8. HTTP Clients

Replace `Net::HTTP` or other blocking HTTP clients with `async-http`:

```ruby
require 'async/http/internet'

Async do
  internet = Async::HTTP::Internet.new
  response = internet.get('https://api.example.com/data')
  puts response.read
end
```

## 9. Timeouts

### Thin:
```ruby
EM::Synchrony.run do
  Timeout::timeout(5) do
    # Your code here
  end
end
```

### Falcon:
```ruby
Async do |task|
  task.with_timeout(5) do
    # Your code here
  end
end
```

## 10. Graceful Shutdown

### Thin:
```ruby
trap('INT') do
  puts "Stopping..."
  EM.stop
end
```

### Falcon:
```ruby
Async.run do |task|
  server = Falcon::Server.new
  task.async do
    server.run
  end

  Signal.trap('INT') do
    puts "Shutting down gracefully..."
    server.stop
    task.stop
  end

  task.wait
end
```

## 11. Logging

Replace any EM-specific logging with standard Ruby logging or async-compatible logging:

```ruby
require 'async/logger'

logger = Async::Logger.new(STDOUT)
logger.info "Application started"
```

## 12. Testing

Update your test suite to be async-aware:

```ruby
require 'async/rspec'

RSpec.describe 'AsyncOperation', type: :request do
  include_context Async::RSpec::Reactor

  it 'performs asynchronous operation' do
    Async do
      result = perform_async_operation
      expect(result).to eq('expected value')
    end
  end
end
```

Remember to thoroughly test your application after migration, paying special attention to areas involving concurrency, I/O operations, and third-party service interactions.

**Comment by delano** [comment]
### [Event-Based Ruby Web Servers.md](https://github.com/user-attachments/files/16922958/Event-Based.Ruby.Web.Servers.md)

# Running Falcon as a Service in Debian 12

## Prerequisites
- Debian 12 installed
- Ruby and Falcon gem installed
- Your Rack application ready

## Steps to Create a Falcon Service

1. Create a service file:
   ```bash
   sudo nano /etc/systemd/system/falcon-app.service
   ```

2. Add the following content to the file:
   ```ini
   [Unit]
   Description=Falcon web server
   After=network.target

   [Service]
   Type=simple
   User=www-data
   WorkingDirectory=/path/to/your/app
   ExecStart=/usr/local/bin/falcon host -c /path/to/your/app/config.ru
   Restart=on-failure
   Environment=RACK_ENV=production

   [Install]
   WantedBy=multi-user.target
   ```

   Replace `/path/to/your/app` with the actual path to your application.

3. Save and exit the editor (in nano, press Ctrl+X, then Y, then Enter).

4. Reload systemd to recognize the new service:
   ```bash
   sudo systemctl daemon-reload
   ```

5. Start the Falcon service:
   ```bash
   sudo systemctl start falcon-app
   ```

6. Enable the service to start on boot:
   ```bash
   sudo systemctl enable falcon-app
   ```

7. Check the status of the service:
   ```bash
   sudo systemctl status falcon-app
   ```

## Managing the Falcon Service

- To stop the service:
  ```bash
  sudo systemctl stop falcon-app
  ```

- To restart the service:
  ```bash
  sudo systemctl restart falcon-app
  ```

- To view logs:
  ```bash
  sudo journalctl -u falcon-app
  ```

## Troubleshooting

If you encounter issues:

1. Check the logs:
   ```bash
   sudo journalctl -u falcon-app -f
   ```

2. Ensure the paths in the service file are correct.

3. Verify that the `www-data` user has necessary permissions to the application directory.

4. Make sure Falcon is installed and accessible in the system path.

**Comment by jmtsi** [comment]
I hope that the evaluation includes testing with IPv6. The current thin-server doesn't support IPv6 at all, which is a bummer.

**Comment by delano** [comment]
### Concerning, open issues

> "Hi, I'm migrating puma->falcon for a quiet loaded app 200-500 req/s,
> average response time is below 30ms, once on falcon the memory usage
> started growing over time quiet fast" -- https://github.com/socketry/falcon/issues/154

> "Falcon generally has, IMHO, better request queueing/processing than Puma,
> but it's still quite young in comparison to Puma, so some growing pains
> are to be expected." --https://github.com/socketry/falcon/issues/277

> "Currently, it appears that only TLS 1.2 is working. It increases
> round-trip latency." -- https://github.com/socketry/falcon/issues/105

> "Falcon not working properly locally on MacOS (m1) in forked mode https://github.com/socketry/falcon/issues/225"
> "Limiting incoming requests queue https://github.com/socketry/falcon/issues/212"
> "errors on production, socket fail https://github.com/socketry/falcon/issues/254"
