### ISSUE TITLE
Implement Named Views in Vue.js Router

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#677]
Title: Implement Named Views in Vue.js Router

### Description:
Implement support for named views in Vue.js router to allow multiple components to be rendered simultaneously for a single route. This feature will enhance the flexibility of our routing system and enable more complex layouts.

### Tasks:
- [x] Research Vue Router's current capabilities and limitations
- [ ] Design the API for defining named views in route configurations
- [ ] Implement the core functionality to render multiple named views
- [ ] Update the Vue Router documentation to include named views
- [ ] Create examples and test cases to demonstrate usage

### Design Considerations:
- Ensure compatibility with existing Vue Router features
- Consider how named views will interact with nested routes
- Design a clear and intuitive API for developers to define named views
- Evaluate performance implications of rendering multiple components simultaneously

<details>
<summary>Additional Context</summary>

Named views allow developers to define multiple router-view components in a template and map route components to them. This is particularly useful for complex layouts where different sections of the page need to be populated with different components based on the current route.

Example usage:
```html
<router-view name="header"></router-view>
<router-view></router-view>
<router-view name="footer"></router-view>
```

Corresponding route configuration:
```javascript
const router = createRouter({
  routes: [
    {
      path: '/',
      components: {
        default: Home,
        header: Header,
        footer: Footer
      }
    }
  ]
})
```

This feature will greatly enhance the flexibility of Vue.js applications, allowing for more dynamic and complex layouts driven by routing.
</details>
