### ISSUE TITLE
Enhance Docker Build Workflow: Add Manifest and Improve Tagging Strategy

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#683]
Description:
We want to improve our Docker build workflow by adding a manifest for multi-architecture builds and refining our image tagging strategy. This will enhance our CI/CD process and make our Docker images more versatile and maintainable.

https://github.com/onetimesecret/onetimesecret/pkgs/container/onetimesecret

### Tasks:
- [ ] Add Docker manifest to multi-arch builds via GitHub Action
- [ ] Implement new tagging strategy:
  - [ ] Use `next` tag on `develop` branch by default
  - [ ] Only tag `latest` for version releases with `rc` in the tag

### Technical Considerations:
1. The existing GitHub Actions workflow will need to be modified to incorporate the manifest creation step.
2. The tagging logic in the `docker/metadata-action` step should be updated to reflect the new strategy.
3. We may need to adjust the `build-and-push` step to ensure it works correctly with the new manifest.

### Potential Pitfalls:
- Ensuring backwards compatibility with existing deployment processes that may rely on the current tagging scheme.
- Properly handling edge cases in the tagging logic (e.g., non-RC releases, hotfixes).

<details>
<summary>Current GitHub Actions Workflow</summary>

```yaml
name: Docker

on:
  push:
    tags: [ "v*" ]
  pull_request:
    types: [closed]
    branches: [ "develop", "feature/*", "rel/*" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_IMAGE_NAME: ${{ github.repository }}
  RACK_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: arm64

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            # set latest tag for master branch
            type=raw,value=next,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.DOCKERHUB_IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
```
</details>
