### ISSUE TITLE
Update Front-End Libraries for OnetimeSecret v0.18.1

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#687]
### Description
This is a regular maintenance ticket to update the front-end libraries for OnetimeSecret. Our current version is 0.18.0, and we need to ensure all dependencies are up-to-date to maintain security, performance, and compatibility.

### Tasks
- [ ] Review and update all production dependencies
- [ ] Review and update all development dependencies
- [ ] Test the application thoroughly after updates
- [ ] Update documentation if any API changes occur
- [ ] Update the changelog

### Technical Considerations
- Pay special attention to major version upgrades, particularly for Vue (currently ^3.5.11) and Vue Router (^4.4.0)
- Check for any breaking changes in Pinia (^2.2.4) and Vue I18n (10.0.3)
- Ensure compatibility between updated libraries, especially with Vite (^5.3.4) and TypeScript (^5.5.3)

### Opportunities for Improvement
- Consider adopting Vue 3's Composition API more extensively if not already done
- Evaluate if newer features in updated libraries can improve our codebase or user experience

<details>
<summary>Detailed Dependency List</summary>

```json
{
  "dependencies": {
    "@headlessui/vue": "^1.7.22",
    "@intlify/core": "^9.14.1",
    "altcha": "^1.0.0",
    "axios": "^1.7.7",
    "pinia": "^2.2.4",
    "pnpm": "^9.6.0",
    "stripe": "^16.6.0",
    "vue": "^3.5.11",
    "vue-i18n": "10.0.3"
  },
  "devDependencies": {
    "@eslint/js": "^9.7.0",
    "@iconify-json/heroicons": "^1.1.22",
    "@iconify-json/mdi": "^1.2.0",
    "@iconify/vue": "^4.1.2",
    "@intlify/eslint-plugin-vue-i18n": "^3.0.0",
    "@pinia/testing": "^0.1.0",
    "@tailwindcss/forms": "^0.5.7",
    "@tailwindcss/typography": "^0.5.13",
    "@tsconfig/node22": "^22.0.0",
    "@types/node": "^20.14.11",
    "@typescript-eslint/eslint-plugin": "^7.16.1",
    "@typescript-eslint/parser": "^7.16.1",
    "@vitejs/plugin-vue": "^5.0.5",
    "@vitest/coverage-v8": "^2.1.2",
    "@vue/runtime-core": "^3.4.38",
    "@vue/test-utils": "^2.3.0",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-plugin-vue": "^9.27.0",
    "globals": "^15.8.0",
    "jsdom": "^25.0.1",
    "postcss": "^8.4.39",
    "rimraf": "^6.0.1",
    "rollup": "^4.24.0",
    "tailwindcss": "^3.4.6",
    "ts-node": "^10.9.2",
    "typescript": "^5.5.3",
    "typescript-eslint": "^7.16.1",
    "vite": "^5.3.4",
    "vite-plugin-html": "^3.2.2",
    "vitest": "^2.1.2",
    "vue-router": "^4.4.0",
    "vue-tsc": "^2.0.26"
  }
}
```

</details>
