### ISSUE TITLE
Set up End-to-End testing with Playwright and GitHub Actions integration

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#709]
Onetime Secret provides secure, one-time sharing of sensitive information. To ensure our service remains reliable and trustworthy, we need to implement robust end-to-end testing. Playwright offers a powerful solution for this, allowing us to verify our core functionality across different browsers and scenarios.

### Tasks:
- [ ] Set up Playwright in the project
- [ ] Create test cases covering critical flows, especially secret creation and one-time viewing
- [ ] Implement GitHub Action for automated Playwright testing
- [ ] Document testing procedures for the development team

### Importance:
1. Maintain trust: Verify that each secret link works only once and then disappears forever
2. Cross-browser reliability: Test functionality in Chromium, Firefox, and WebKit
3. Ensure consistent user experience across different scenarios

### Technical Considerations:
- Playwright supports testing in multiple browsers (Chromium, Firefox, WebKit)
- Tests can be written in JavaScript/TypeScript
- GitHub Action will run tests on every push and pull request to main/master branches

### GitHub Action Configuration:
```yaml
name: Playwright Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```
