### ISSUE TITLE
Investigate and Implement @intlify/unplugin-vue-i18n for Enhanced i18n Workflow

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#711]
### Description
We aim to explore and potentially integrate @intlify/unplugin-vue-i18n into our Vue.js project to improve our internationalization (i18n) workflow. This plugin offers build-time optimizations, automatic resource importing, and better code splitting for locale messages, which could significantly enhance our development process and application performance.

### TODO
- [ ] Research @intlify/unplugin-vue-i18n features and benefits
- [ ] Set up a test implementation in a development branch
- [ ] Evaluate performance improvements and development workflow enhancements
- [ ] Create documentation for team on how to use new i18n features (if implemented)
- [ ] Update build configuration to include the plugin (if approved)

### Design Considerations
- Improved developer experience with custom blocks in Single-File Components for i18n
- Potential for better application performance through message compilation and efficient code splitting
- Enhanced type checking for i18n messages when used with TypeScript

### Opportunities for Improvement
- Streamline the process of extracting and managing translatable strings
- Reduce manual work in importing and managing locale files
- Improve runtime performance of internationalized content

<details>
<summary>Current i18n Implementation Details</summary>

Our current implementation uses vue-i18n directly, as seen in the SecretContentInputArea.vue component:

```vue
<textarea
  :placeholder="$t('web.COMMON.secret_placeholder')"
  aria-label="Enter the secret content to share here">
</textarea>
```

Integrating @intlify/unplugin-vue-i18n could potentially simplify this process and provide more robust tooling for managing these translations.
</details>
