### ISSUE TITLE
Implement vue-i18n-extract for Enhanced i18n Management

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#712]
Related to #711

### Description
We want to explore and implement vue-i18n-extract (https://github.com/Spittal/vue-i18n-extract) to improve our internationalization (i18n) workflow. This tool will help us identify missing and unused translation keys, potentially add missing keys automatically, and generate reports for better i18n management.

### TODO
- [ ] Install vue-i18n-extract as a dev dependency
- [ ] Set up initial configuration for vue-i18n-extract
- [ ] Run vue-i18n-extract on our codebase to identify current i18n issues
- [ ] Evaluate the results and decide on next steps (e.g., adding missing keys, removing unused keys)
- [ ] Integrate vue-i18n-extract into our CI/CD pipeline
- [ ] Update documentation for the team on how to use vue-i18n-extract

### Opportunities for Improvement
- Automate the process of identifying and managing missing translation keys
- Reduce manual effort in maintaining i18n files
- Improve code quality by removing unused translation keys
- Enhance developer experience with better i18n tooling

<details>
<summary>Current i18n Usage Example</summary>

Our current implementation uses vue-i18n directly, as seen in the SecretContentInputArea.vue component:

```vue
<textarea
  :placeholder="$t('web.COMMON.secret_placeholder')"
  aria-label="Enter the secret content to share here">
</textarea>
```

Implementing vue-i18n-extract will help us ensure all such usages are properly managed and tracked.
</details>
