### ISSUE TITLE
Harmonize COPY --link behavior between Docker and Podman builds

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#722]
### Description
There's a discrepancy in how Docker and Podman parse the `COPY` command in Dockerfiles, specifically regarding the `--link` flag. This inconsistency prevents us from fully utilizing the `--link` functionality, which could potentially improve build performance and reduce image size.

- Docker supports `COPY --link` but doesn't allow it as a build arg (e.g., `COPY --link=$LINK_FLAG`)
- Podman (Buildah) doesn't support `COPY --link`, but does support `COPY --link=false`
- Neither fully supports a dynamic approach to enable/disable the feature based on the build environment

### Why `--link` Matters
The `--link` flag is important for several reasons:
1. Performance: It can significantly speed up the build process by creating hard links instead of copying files when possible.
2. Reduced Disk Usage: Hard links don't duplicate file data, potentially reducing the overall size of Docker images.
3. Improved Caching: Better caching can lead to faster subsequent builds.
4. Consistency: Ensures copied files are identical to source files, including metadata.
5. Atomic Operations: Copy operations are atomic, preventing issues with partially copied files.

These benefits can lead to faster builds, smaller images, and more efficient use of resources, which is particularly valuable in CI/CD pipelines and production environments.

### TODO
- [ ] Research latest updates to Docker and Podman (Buildah) for any recent changes in `--link` support
- [ ] Devise a cross-compatible solution that works for both Docker and Podman builds
- [ ] Update our Dockerfile to implement the solution
- [ ] Test the updated Dockerfile with both Docker and Podman
- [ ] Document the solution and any caveats for future reference

### Technical Considerations
- Docker already supports build args for `--chmod=$MODE`, which could serve as a precedent for `--link`
- Podman's support for `--link=false` suggests potential for future `--link=true` implementation
- A multi-stage build approach might be necessary to accommodate both Docker and Podman peculiarities

<details>
<summary>Relevant Dockerfile Excerpt</summary>

```Dockerfile
# syntax=docker/dockerfile:1.10
# check=error=true

##
# ONETIME SECRET - DOCKER IMAGE - 2024-10-07
#
# ... [truncated for brevity] ...

## Copy only necessary files from previous stages
COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build $CODE_ROOT/public $CODE_ROOT/public
COPY --from=build $CODE_ROOT/templates $CODE_ROOT/templates
COPY --from=build $CODE_ROOT/src $CODE_ROOT/src
COPY bin $CODE_ROOT/bin
COPY etc $CODE_ROOT/etc
COPY lib $CODE_ROOT/lib
COPY migrate $CODE_ROOT/migrate
COPY VERSION.yml config.ru Gemfile Gemfile.lock .commit_hash.txt $CODE_ROOT/

# ... [remaining Dockerfile content truncated] ...
```
</details>

### Relevant Links
- [Buildah Documentation](https://github.com/containers/buildah/tree/main/docs/containertools)
- [Docker BuildKit PR for --link](https://github.com/moby/buildkit/pull/5151)
- [Docker Dockerfile Release Notes](https://docs.docker.com/build/buildkit/dockerfile-release-notes/#1100)
- [Docker COPY Reference](https://docs.docker.com/reference/dockerfile/#copy---link)
