### ISSUE TITLE
Enhance CSRF Token Validation with Constant-Time Comparison

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#726]
### Description
The current implementation of the `shrimp?` method in `lib/onetime/models/session.rb` performs a string comparison for CSRF token validation. While functional, it could be improved by using a constant-time comparison method for enhanced security.

### TODO
- [ ] Implement constant-time comparison for CSRF token validation
- [ ] Review and update token generation process (if necessary)
- [ ] Implement proper token lifecycle management

### Technical Considerations
<details>
<summary>Click to expand</summary>

1. Consider using `Rack::Utils.secure_compare` or `ActiveSupport::SecurityUtils.secure_compare` for constant-time comparison.
2. Ensure the token generation process uses a cryptographically secure random number generator.
3. Implement proper token lifecycle management (generation, storage, rotation).

Current Timing Attack Resistance:
The code uses Ruby's built-in string comparison (==), which is typically implemented as a timing-safe comparison for strings in modern Ruby versions (since Ruby 2.3). This mitigates the risk of timing attacks, where an attacker could potentially guess the token by analyzing the time taken for comparisons.

Example implementation:
```ruby
def shrimp?(guess)
  shrimp = self.shrimp.to_s
  guess = guess.to_s
  (!shrimp.empty?) && Rack::Utils.secure_compare(shrimp, guess)
end
```
</details>

### Potential Pitfalls
1. Switching to a constant-time comparison method may have a slight performance impact, although it should be negligible in most cases.
2. Ensure that the change doesn't break any existing functionality or tests.
3. Be cautious of any dependencies introduced by using framework-specific methods like `Rack::Utils.secure_compare`.
