### ISSUE TITLE
Update Open Graph and Twitter Card Meta Tags in Server-Side Templates

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#728]
Description:
We need to update our server-side templates to include the latest Open Graph and Twitter Card meta tags. This will improve our website's appearance when shared on social media platforms.

### Tasks:
- [ ] Update Facebook Open Graph meta tags
- [ ] Update Twitter Card meta tags
- [ ] Ensure all dynamic content placeholders are correctly implemented
- [ ] Test the updated meta tags with social media preview tools

### Technical Considerations:
1. Ensure that the `{{baseuri}}`, `{{page_title}}`, `{{description}}`, and `{{site_host}}` placeholders are correctly populated on the server-side.
2. Verify that the `/img/social-preview.png` image exists and is optimized for social media sharing.
3. Consider implementing dynamic image generation for social media previews based on page content.

<details>
<summary>Existing Meta Tags</summary>

```html
<meta charset="UTF-8">
<meta name="referrer" content="no-referrer">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{{page_title}}</title>

<!-- OG Meta Tags -->
<meta property="og:url" content="{{baseuri}}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{page_title}}">
<meta property="og:description" content="{{description}}">
<meta property="og:image" content="/img/social-preview.png">

<!-- X Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="{{site_host}}">
<meta property="twitter:url" content="{{baseuri}}">
<meta name="twitter:title" content="{{page_title}}">
<meta name="twitter:description" content="{{description}}">
<meta name="twitter:image" content="/img/social-preview.png">

<!-- Additional meta tags omitted for brevity -->
```
</details>

### Potential Pitfalls:
1. Inconsistent rendering of meta tags across different page templates
2. Incorrect or missing data in dynamic content placeholders
3. Performance impact of generating dynamic social media preview images

By addressing these considerations, we can ensure that our website's social media presence is optimized and consistent across various platforms.

### Some preview cards from Canvas

![2](https://github.com/user-attachments/assets/291f76d6-7837-4d33-ad1a-933604c79c6d)
![Title 1280x640](https://github.com/user-attachments/assets/7f87631a-fff8-4763-ad04-1e075a34996c)
![1](https://github.com/user-attachments/assets/5abdc19f-32c5-47e9-bd5d-faf865bccd42)
![Title 1280x640](https://github.com/user-attachments/assets/83231a05-4a8d-4174-9051-a396c2da788c)
