### ISSUE TITLE
Fix Broken Password Reset Flow

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#730]
### Description
The password reset functionality is currently not working as expected. Users who attempt to reset their passwords are encountering issues that prevent them from completing the process. This is a critical issue affecting user account access and needs to be addressed promptly.

### Current Behavior
1. Users initiate the password reset process from the sign-in page.
2. They receive a password reset email with a link.
3. Clicking the link leads to a page that fails to load properly.

### Expected Behavior
1. Users should be able to initiate the password reset process from the sign-in page.
2. They should receive a password reset email with a valid link.
3. Clicking the link should lead to a functional password reset page.
4. Users should be able to enter and confirm a new password.
5. Upon successful password reset, users should be able to log in with their new credentials.

### TODO
- [ ] Investigate why the password reset page is not loading
- [ ] Fix any backend issues preventing the reset page from functioning
- [ ] Ensure the frontend components for password reset are working correctly
- [ ] Test the entire password reset flow from initiation to completion
- [ ] Update error handling to provide clear feedback if issues occur during the process

### Technical Considerations
- Review the `PasswordReset.vue` component to ensure it's properly implemented and integrated.
- Check the routing configuration to make sure the password reset page is accessible.
- Verify that the backend API endpoints for password reset are functioning correctly.
- Ensure proper error handling and user feedback throughout the process.
- Consider implementing logging for password reset attempts to aid in debugging and monitoring.

<details>
<summary>Relevant Code Snippets</summary>

```vue
<!-- PasswordReset.vue -->
<template>
  <!-- Password reset form implementation -->
</template>

<script setup lang="ts">
// Password reset logic
</script>
```

```vue
<!-- Signin.vue -->
<template>
  <div class="text-center">
    <ul class="space-y-2">
      <!-- ... -->
      <li>
        <router-link to="/forgot"
                     class="text-sm text-gray-600 dark:text-gray-400 hover:underline transition duration-300 ease-in-out"
                     aria-label="Forgot Password">
          {{ $t('web.login.forgot_your_password') }}
        </router-link>
      </li>
    </ul>
  </div>
</template>
```
</details>
