### ISSUE TITLE
Create Dockerfile-lite for All-in-One Onetime Secret Container

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#742]
### Description

Develop a Dockerfile-lite that combines Onetime Secret and Redis into a single container for simplified deployment and testing. This all-in-one container will provide an ephemeral, self-contained environment that aligns with the temporary nature of one-time secrets.

### TODO

- [x] Create Dockerfile-lite based on the existing Onetime Secret image
- [x] Install and configure Redis within the container
- [x] Develop a startup script to launch both services
- [x] Set appropriate environment variables for Onetime Secret
- [x] Test the container for functionality and performance
- [x] Update documentation with usage instructions and considerations

### Technical Considerations

- Ensure proper isolation between Onetime Secret and Redis within the container
- Configure Redis to only listen on localhost for security
- Optimize container size by removing unnecessary packages and files
- Consider using multi-stage builds to reduce final image size
- Implement health checks for both Onetime Secret and Redis services

<details>
<summary>Dockerfile-lite Overview</summary>

```dockerfile
FROM ghcr.io/onetimesecret/onetimesecret

# Install Redis and other dependencies
RUN apt-get update && apt-get install -y \
    redis-server \
    redis-tools \
    && rm -rf /var/lib/apt/lists/*

# Write Redis configuration
RUN <<-EOF cat > /etc/redis/redis.conf
    bind 0.0.0.0
    port 6379
    daemonize no
EOF

# Write the startup script
RUN <<-'EOF' cat > /start.sh
#!/bin/bash
set -e

# Start Redis server
redis-server /etc/redis/redis.conf &

# Wait for Redis to be ready
until redis-cli ping; do
  echo "Waiting for Redis to be ready..."
  sleep 1
done

# Start Onetime Secret
exec /app/bin/entrypoint.sh
EOF

RUN chmod +x /start.sh

# Set environment variables
ENV HOST=0.0.0.0:3000
ENV PORT=3000
ENV STDOUT_SYNC=true
ENV SSL=false
ENV COLONEL=admin@example.com
ENV REDIS_URL=redis://localhost:6379/0
ENV RACK_ENV=production
ENV AUTH_ENABLED=false

EXPOSE 3000

CMD ["/start.sh"]
```
</details>

### Potential Pitfalls

1. Security concerns with running both services in a single container
2. Potential resource conflicts between Onetime Secret and Redis
3. Difficulty in scaling individual components separately
4. Increased complexity in debugging issues within the container
5. Possible performance impact due to shared resources
