### ISSUE TITLE
Update Styling for Footer Links and Language Toggle

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#744]
### Description
We need to update the footer links and improve the styling of the language toggle component in the footer. This includes adjusting the opacity of the language toggle and ensuring it responds to user interactions correctly.

### Tasks
- [x] Review and update footer links as needed
- [x] Implement opacity changes for the language toggle
- [x] Ensure language toggle responds to hover and open states
- [ ] Test accessibility of the updated footer components

### Design considerations
- The links should looks fine regardless of the display settings for individual links (e.g. signin disabled)
- The language toggle should have lower opacity by default
- On hover, the language toggle should increase to 100% opacity
- When the language menu is open, the toggle should maintain 100% opacity
- Consider the contrast and readability of the footer links and toggle in both light and dark modes

<details>
<summary>Implementation Details</summary>

For the language toggle opacity changes, modify the DefaultFooter.vue and LanguageToggle.vue components:

1. In DefaultFooter.vue:
   - Add a state to track if the language menu is open
   - Apply conditional classes for opacity based on the menu state

2. In LanguageToggle.vue:
   - Emit an event when the menu state changes
   - Ensure the parent component (DefaultFooter) can react to these changes

Example code snippet for DefaultFooter.vue:
```vue
<div class="relative z-50" 
     :class="{ 'opacity-50 hover:opacity-100': !isLanguageMenuOpen }"
     aria-label="Change language">
  <LanguageToggle @menu-toggled="handleMenuToggled" />
</div>
```

These changes will improve the visual feedback and user experience of the language toggle in the footer.
</details>
