### ISSUE TITLE
Rename `:secret` to `:secret_key` in site configuration for clarity and consistency

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#746]
### Description
We want to improve the clarity and consistency of our configuration by renaming the `:secret` key to `:secret_key` in the site configuration. This change will better align with our new `:secret_options` structure and make the purpose of this configuration more explicit.

### TODO
- [ ] Update the configuration loading process to use `:secret_key` instead of `:secret`
- [ ] Implement backward compatibility to support existing configurations using `:secret`
- [ ] Update documentation to reflect the new naming convention
- [ ] Test the changes to ensure no breaking changes for existing setups

### Technical Considerations
- The change should be backward compatible to avoid breaking existing installations.
- We need to carefully update all references to this configuration key throughout the codebase.
- Consider adding a deprecation warning for the old `:secret` key usage.

<details>
<summary>Relevant Code Context</summary>

```yaml
  # IMPORTANT: After setting the secret key, it should not be changed.
  # Be sure to create and store a backup in a secure offsite
  # location. Changing the secret can lead to unforeseen issues
  # like not being able to decrypt existing secrets.
  :secret_key: <%= ENV['SECRET_KEY'] || ENV['SECRET'] || 'CHANGEME' %>
```

```ruby
module Onetime
  module Config
    # ... (previous code)

    def after_load(conf = nil)
      conf ||= {}

      # Backwards compatibility
      unless conf[:site]&.key?(:secret_key)
        conf[:site][:secret_key] = conf[:site][:secret]
      end

      # ... (rest of the method)
    end

    # ... (rest of the module)
  end
end
```
</details>

### Potential Pitfalls
1. Overlooking places where the old `:secret` key is used directly might lead to runtime errors.
2. If not implemented carefully, this change could potentially expose the secret key in logs or error messages during the transition period.
3. Third-party integrations or plugins relying on the old configuration structure might break if not updated accordingly.
