### ISSUE TITLE
Refactor and Optimize Locale Handling in OT::App

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#792]
### Description
We want to improve the locale handling logic in our `OT::App` module, specifically focusing on the `carefully` method and `check_locale!` method. The current implementation has redundant checks, excessive logging, and potential inefficiencies. We'd like to consolidate the logic, reduce logging to a helpful minimum, and ensure a clear narrative of locale selection across both methods.

### TODO
- [x] Consolidate locale determination logic in `check_locale!` method
- [x] Reduce logging to key decision points
- [x] Ensure clear indication of which locale was selected and why
- [x] Simplify the locale selection process
- [x] Remove redundant checks and inefficient array operations
- [x] Maintain a clear priority: given locale > rack locales > default locale
- ~Update `carefully` method to use the result from `check_locale!`~

### Technical Considerations
- The refactored code should maintain compatibility with existing locale-related configurations (`OT.conf[:locales]`, `OT.locales`)
- Consider the impact on performance, especially regarding the reduction of array operations
- Ensure that the selected locale is always available and valid
- Maintain the existing behavior where `Content-Language` header is set based on the selected locale

<details>
<summary>Current Implementation Details</summary>

```ruby
def carefully(redirect=nil, content_type=nil, app: :web)
  # ... existing code ...

  OT.ld "Checking Content-Language header"
  if res.header['Content-Language']
    OT.ld "Content-Language already set to: #{res.header['Content-Language']}"
  else
    OT.ld "Content-Language not set, determining language"
    content_language = req.env['ots.locale'] || req.env['rack.locale'] || OT.conf[:locales].first
    OT.ld "Selected Content-Language: #{content_language}"
    OT.ld "Source: #{if req.env['ots.locale']
                      'ots.locale'
                      else
                      (req.env['rack.locale'] ? 'rack.locale' : 'OT.conf[:locales].first')
                      end}"
    res.header['Content-Language'] = content_language
    OT.ld "Set Content-Language header to: #{res.header['Content-Language']}"
  end

  # ... rest of the method ...
end

def check_locale! locale=nil
  # ... existing implementation ...
end
```
</details>

### Potential Pitfalls
- Changing the locale selection logic might affect existing user experiences or expectations
- Reducing logging too much could make debugging more difficult in the future
- Ensure that the refactored code handles edge cases, such as invalid locales or missing configurations
- Be cautious about introducing breaking changes to any public API or behavior related to locale handling
