### ISSUE TITLE
Create useCustomDomains composable for dynamic domain management

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#802]
### Description
We want to replace the current static handling of custom domains with a more dynamic and feature-rich solution using a Vue composable. This will better handle domain verification states and provide a more maintainable approach to domain management across the application.

### Tasks
- [x] Create `useCustomDomains` composable
- [x] Migrate existing domain logic from SecretForm to the composable
- [x] Add domain verification status tracking
- [x] Update type definitions to include verification status
- [x] Implement reactive state management (possibly using Pinia)
- [ ] ~Update SecretContentInputArea to use new composable~
- [ ] #938

### Technical Considerations
<details>
<summary>Implementation Details</summary>

- Consider using Pinia for state management, similar to the CSRF store pattern
- The composable should handle:
  - Available domains list
  - Default domain management
  - Domain verification states
  - Local storage persistence
  - Domain selection history
- Need to ensure backward compatibility with existing `window.custom_domains` usage
</details>

### Potential Pitfalls
- State synchronization between window object and store
- Race conditions during domain verification checks
- Handling edge cases when domains become unverified
- Migration path for existing implementations
- Performance impact of additional verification checks

### Type Definitions Update
```typescript
interface CustomDomain {
  domain: string;
  isVerified: boolean;
  lastVerified?: Date;
}

interface Window {
  custom_domains_record_count?: number;
  custom_domains?: CustomDomain[];
}
```
