### ISSUE TITLE
Revisit Confirmation (i.e. "Metadata") Page 

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#808]
### Description
We want to improve the user experience of the secret confirmation page by creating a clearer visual hierarchy and more intuitive interactions. The current design presents all information with equal weight, making it difficult for users to focus on the primary task of copying and sharing the secret link.

### TODOs
- [ ] Restructure page layout into three distinct zones (Primary/Secondary/Tertiary)
- [ ] Implement improved copy mechanism with clear feedback states
- [ ] Add subtle animations for state changes
- [ ] Redesign status indicators and lifecycle information
- [ ] Move FAQ to expandable section or separate page
- [ ] Add progress indicator for expiration time

### Design Considerations
- Primary zone should prominently feature the secret link and copy mechanism
- Secondary zone should display status/lifecycle info in a glanceable format
- Tertiary zone should contain additional actions without competing for attention
- Use white space and subtle animations to create a sense of hierarchy
- Implement progressive disclosure for advanced features

<details>
<summary>Detailed UX Analysis</summary>

#### Core User Needs
1. Securely copy and share one-time secret link
2. Understand secret's lifecycle (expiration, burn status)

#### Current Issues
- Flat information hierarchy
- Visual noise from competing elements
- Unclear primary action guidance
- Cognitive load from immediate FAQ presentation

#### Emotional Design Goals
- Create sense of security through calm, confident design
- Provide clear feedback through micro-interactions
- Maintain focus on primary task
</details>

### Opportunities for Improvement
1. Enhanced copy mechanism
   - Automated text selection
   - Clear success/copied state
   - Natural state transitions

2. Visual Hierarchy
   - Clear separation of concerns
   - Purposeful use of color for status
   - Improved spacing and rhythm

3. User Flow
   - Immediate confirmation feedback
   - One-click copy functionality
   - Clear expiration visibility
   - Easy access to secondary actions

4. Progressive Enhancement
   - Move advanced features behind expandable sections
   - Simplify initial view for focused interaction
   - Surface additional options contextually

### Suggested Implementation

Let's start with a code example that implements these improvements:

<details>
<summary>Detailed UX Analysis</summary>

```vue src/views/secrets/ShowMetadata.vue
<template>
  <div class="secret-confirmation">
    <!-- Primary Zone: Secret Link -->
    <div class="secret-confirmation__primary">
      <div class="status-indicator">
        <CheckCircleIcon class="icon-success" />
        <span>Secret Created Successfully</span>
      </div>
      
      <div class="secret-link-container" :class="{ 'is-copied': isCopied }">
        <input 
          ref="secretLink"
          type="text"
          readonly
          :value="secretUrl"
          class="secret-link-input"
        />
        <button 
          class="copy-button"
          @click="copySecretLink"
          :disabled="isCopied"
        >
          <span v-if="!isCopied">Copy Link</span>
          <span v-else class="copied-text">
            <CheckIcon class="icon-small" />
            Copied!
          </span>
        </button>
      </div>
    </div>

    <!-- Secondary Zone: Status & Lifecycle -->
    <div class="secret-confirmation__secondary">
      <div class="expiration-indicator">
        <div class="expiration-progress" :style="{ width: expirationProgress + '%' }"></div>
        <span>Expires {{ expirationTimeFormatted }}</span>
      </div>
      
      <div class="lifecycle-status">
        <BurnIcon v-if="isOneTime" class="icon-burn" />
        <span>{{ lifecycleMessage }}</span>
      </div>
    </div>

    <!-- Tertiary Zone: Actions -->
    <div class="secret-confirmation__tertiary">
      <button class="action-button" @click="burnSecret" v-if="canBurn">
        Burn Secret Now
      </button>
      <button class="action-button" @click="createNew">
        Create New Secret
      </button>
      
      <div class="help-section">
        <button class="help-toggle" @click="toggleHelp">
          Need Help? <ChevronDownIcon :class="{ 'is-expanded': isHelpExpanded }" />
        </button>
        <div v-if="isHelpExpanded" class="help-content">
          <!-- ... existing code ... -->
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { CheckCircleIcon, CheckIcon, BurnIcon, ChevronDownIcon } from '@heroicons/vue/24/outline'

const secretLink = ref(null)
const isCopied = ref(false)
const isHelpExpanded = ref(false)

const expirationProgress = computed(() => {
  // ... existing code ...
})

const lifecycleMessage = computed(() => {
  return props.isOneTime 
    ? 'This secret will be destroyed after first view'
    : 'This secret can be viewed multiple times until expiration'
})

const copySecretLink = async () => {
  try {
    await navigator.clipboard.writeText(props.secretUrl)
    isCopied.value = true
    setTimeout(() => {
      isCopied.value = false
    }, 2000)
  } catch (error) {
    // Fallback to manual copy
    secretLink.value?.select()
    document.execCommand('copy')
  }
}

const toggleHelp = () => {
  isHelpExpanded.value = !isHelpExpanded.value
}
</script>

<style scoped>
.secret-confirmation {
  display: flex;
  flex-direction: column;
  gap: 2rem;
  max-width: 600px;
  margin: 0 auto;
}

.secret-confirmation__primary {
  background: white;
  padding: 2rem;
  border-radius: 0.75rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.status-indicator {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 1rem;
  color: var(--color-success);
}

.secret-link-container {
  position: relative;
  transition: all 0.3s ease;
}

.secret-link-input {
  width: 100%;
  padding: 1rem;
  border: 2px solid var(--color-border);
  border-radius: 0.5rem;
  font-family: monospace;
  font-size: 0.875rem;
}

.copy-button {
  position: absolute;
  right: 0.5rem;
  top: 50%;
  transform: translateY(-50%);
  /* ... existing code ... */
}

.copied-text {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  color: var(--color-success);
}

/* Add remaining styles for secondary and tertiary zones */
</style>
```

</details>

This implementation:
1. Creates clear visual zones for different types of information
2. Implements a sophisticated copy mechanism with feedback
3. Shows expiration status with a progress bar
4. Moves help content to an expandable section
5. Uses subtle animations and transitions for state changes
6. Provides clear success indicators and feedback

Would you like me to explain any specific part in more detail or proceed with the remaining styles?

**Comment by delano** [comment]
### v0.18.3
![Screenshot 2024-10-27 at 20 46 52](https://github.com/user-attachments/assets/f58475d9-00b3-4bd3-95d5-e613cffb89e5)

### In progress
![Screenshot 2024-10-27 at 20 45 43](https://github.com/user-attachments/assets/292c390d-bcda-4115-b6ac-c67ae3978862)
