### ISSUE TITLE
Fix: Vue router dynamic import syntax causing blank pages in production

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#813]
### Description
We've identified an issue where certain pages are rendering blank in production while working fine in development. This affects multiple routes including account management and admin pages. The issue stems from incorrect dynamic import syntax in our Vue router configuration.

### Current Behavior
- Pages render correctly in development
- Production shows blank content between header/footer
- No console errors are displayed
- Affects multiple routes in the account and admin sections

### Technical Solution
We need to update our route definitions to use proper dynamic import syntax:

```js
// Current problematic syntax
default: import('@/views/account/AccountIndex.vue')

// Correct syntax
default: () => import('@/views/account/AccountIndex.vue')
```

<details>
<summary>Affected Routes</summary>

- /account
- /account/domains/add
- /account/domains/:domain/verify
- /colonel (admin section)
</details>

### TODO
- [ ] Update route definitions with correct dynamic import syntax
- [ ] Test build locally before deployment
- [ ] Deploy hotfix to production
- [ ] Verify all affected routes are functioning

### Development Notes
Quick local build and deploy process:
```bash
podman build -t ghcr.io/<org>/<repo>:hotfix-<date> .
docker buildx build --platform=linux/amd64,linux/arm64 . -t ghcr.io/<org>/<repo>:hotfix-<date>
podman push ghcr.io/<org>/<repo>:hotfix-<date>
```

### Opportunities for Improvement
- Add route testing to our CI pipeline
- Implement error boundaries for better production debugging
- Consider adding production build verification steps
- Add ESLint rule to catch incorrect dynamic import syntax

### Production Deployment Notes
**Local Build & Push** (faster than GitHub Actions):
```bash
# Login to GHCR.io
podman login ghcr.io -u <username> -p <github-pat>

# Build with specific tag
TAG="hotfix-$(date +%Y%m%d)"
podman build -t ghcr.io/<org>/<repo>:$TAG .

# Verify platform matches production
podman inspect ghcr.io/<org>/<repo>:$TAG --format '{{.Os}}/{{.Architecture}}'

# Push to registry
podman push ghcr.io/<org>/<repo>:$TAG
```

Local build process (~5 mins) is significantly faster than waiting for GitHub Actions (~15-20 mins) when urgent fixes are needed.
