### ISSUE TITLE
Feature: Enhanced ShowSecret View with Company Branding Support

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#816]
### Description
We want to enhance the ShowSecret view to support company-specific branding and additional content elements, making the secret sharing experience more customizable for enterprise users.

### Tasks
- [ ] Add company name field to metadata model
- [ ] Implement optional company logo URL support
- [ ] Create instructions text field for custom messaging
- [ ] Develop mini FAQ content section
- [ ] Add contact information display
- [ ] Support custom CSS injection for branded styling
- [ ] Update API endpoints to handle new fields

### Design Considerations
- Company logo placement should be consistent with existing BrandSettings interface
- FAQ section should be collapsible to maintain clean UI when unused
- Custom CSS should be sanitized to prevent XSS attacks
- Instructions and FAQ should support markdown formatting
- Mobile responsiveness must be maintained with new elements

### Implementation Notes
<details>
<summary>Integration with existing BrandSettings</summary>

The new fields should integrate with the existing BrandSettings interface:
```typescript
export interface BrandSettings {
  logo: string;  // Existing logo field to be coordinated with
  image_encoded: string;
  primary_color: string;
  // ...other existing fields
}
```

Consider extending this interface or creating a new one specifically for ShowSecret view customization.
</details>

### Related Types
- Builds upon existing `MetadataDetails` interface
- May require updates to `SecretDetails` interface for new display options
- Should consider `CustomDomain` integration for enterprise users

**Comment by kfiresmith** [comment]
Looking forward to this!  Thanks for the awesome self-hostable product!
