### ISSUE TITLE
Remove deprecated Entropy module and related digest generation code

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#820]
### Description
We want to remove the long unused Entropy module which was previously used for digest generation but is no longer needed. This will help reduce technical debt and simplify our codebase.

### Technical Considerations
- Module is located in `lib/onetime/models/modules/entropy.rb`
- Currently contains unused Redis-backed entropy value storage
- Affects `Familia::Set` operations on database 11
- Removal should be done carefully to ensure no legacy code still depends on this module

### Tasks
- [x] Verify no current digest generation code references this module
- [x] Remove the Entropy module and its related tests
- [x] Clean up any Redis keys/sets related to entropy values in db 11
- [x] Update documentation to remove any references to the Entropy module

<details>
<summary>Additional Context</summary>

```ruby
# Current implementation uses Redis-backed entropy values
# Located in lib/onetime/models/modules/entropy.rb
module Onetime
  module Entropy
    @values = Familia::Set.new # ...
    # Various unused methods for entropy generation and management
  end
end
```

This module was historically used for digest generation but has been superseded by other methods. Its removal will help maintain a cleaner, more maintainable codebase.
</details>
