### ISSUE TITLE
Add primary color detection for domain logo/icon uploads

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#835]
### Description
We want to enhance our domain image upload functionality by adding automatic primary color detection. This will help maintain consistent branding across the platform and provide valuable color data for theming purposes.

### Technical Considerations
- Need to analyze uploaded images to extract dominant/primary colors
- Color detection should work with all supported image formats (JPEG, PNG, GIF, SVG, WEBP, BMP, TIFF)
- Consider performance impact of color analysis on upload process
- Need to handle edge cases (transparent backgrounds, multi-colored logos)

### TODO
- [ ] Research and select appropriate color extraction library
- [ ] Add color detection to existing `UpdateDomainImage` class
- [ ] Store detected colors in Redis alongside other image metadata
- [ ] Add color information to API response
- [ ] Add tests for color detection functionality
- [ ] Update documentation

<details>
<summary>Implementation Details</summary>

Proposed changes to existing code:
1. Add new field to store primary color: `_image_field['primary_color']`
2. Process color detection after image dimensions are calculated
3. Consider adding array of secondary colors if useful
4. Handle potential failures in color detection gracefully
5. Ensure color values are stored in consistent format (e.g., hex codes)

Example addition to process method:
```ruby
def process
  # existing code...
  
  # Add color detection
  primary_color = detect_primary_color(file_content)
  _image_field['primary_color'] = primary_color
  
  # continue with existing code...
end
```
</details>

### Potential Pitfalls
- Color detection may be CPU-intensive for large images
- Different color detection algorithms may yield varying results
- Need to handle SVG files differently than raster images
- Color extraction might fail for certain edge cases
- Need to consider impact on upload performance
