### ISSUE TITLE
Reorganize API Types: Split Response/Request Types into Dedicated Files

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#838]
### Description
We want to improve the organization of our TypeScript type definitions by separating API-related types into dedicated files. Currently, all API response types are mixed in with other type definitions in `src/types/onetime.d.ts`. We'd like to look at moving these into a more structured layout.

### TODO
- [x] Create new directory structure `src/types/api/`
- [x] Create `types/api/responses.d.ts` for response types
- [x] Create `types/api/requests.d.ts` for request types
- [x] Move all `*ApiResponse` types to responses.d.ts
- [x] Move base response interfaces (`BaseApiResponse`, `ApiRecordResponse`, etc.)
- [x] Update imports in affected files
- [x] Add type documentation where missing

### Technical Considerations
- Existing types appear to be used in both frontend Vue app and backend Ruby integration
- Need to maintain type relationships with base interfaces like `BaseApiRecord`
- Consider implementing barrel exports (index.ts) for cleaner imports
- Type definitions should maintain strict compatibility with Ruby backend responses

<details>
<summary>Current Type Structure</summary>

```typescript
export type ApiTokenApiResponse = ApiRecordResponse<ApiToken>;
export type CustomDomainApiResponse = ApiRecordResponse<CustomDomain>;
export type AccountApiResponse = ApiRecordResponse<Account>;
// ... (additional response types)

export interface BaseApiResponse {
  success: boolean;
}

export interface ApiRecordResponse<T extends BaseApiRecord> extends BaseApiResponse {
  record: T;
  details?: DetailsType;
}
```
</details>

### Potential Pitfalls
- Breaking changes if imports aren't properly updated
- Circular dependencies between type files
- Maintaining type consistency across the frontend/backend boundary
- Need to ensure all dependent files are updated with new import paths
