### ISSUE TITLE
Redis Session Key Management and Structural Refactoring

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#839]
## Current Observations
- `messages` and `shrimp` keys persist without expiration
- Flat key storage is working great but could be easier to manage with a few separate keys.
- Limited segmentation of session-related data

### Key Management
- Implement automatic expiration for session keys
- Add logging/metrics for key lifecycle tracking

### Data Structure Refactoring
- Convert `form_fields` to Redis hash key
- Implement `shrimp` as a specific string key
- Create separate hash key for custom domain validation

### Proposed Redis Structure
```ruby
{
  "session:#{id}:form_fields" => {
    # Hash-based form fields
  },
  "session:#{id}:shrimp" => "specific_shrimp_value",
  "session:#{id}:domain_validation" => {
    # Domain-specific validation data
  },
  "session:#{id}:expiration" => timestamp
}
```

## Tasks
- [ ] Review current session key management in Redis
- [ ] Implement automatic expiration for session-related keys
- [ ] Refactor `form_fields` to use a Redis hash key
- [ ] Convert `shrimp` to a specific string key
- [ ] Implement custom domain validation in a separate hash key
- [ ] Ensure data migration path for existing keys
- [ ] Update related model methods to work with new key structures
- [ ] Add comprehensive unit tests for new key management approach
- [ ] Add logging/metrics for key lifecycle tracking

## Technical Considerations
- Maintain backwards compatibility
- Minimize performance overhead
- Ensure robust error handling
- Provide clear migration strategy

## Potential Risks
- Existing session data migration
- Potential temporary performance impact
- Ensuring all session-related code is updated

## Success Criteria
- Reduced memory usage
- Improved key management
- Clear, predictable session data structure
- No disruption to existing application flows
