### ISSUE TITLE
Add brand setting to control public homepage behavior for custom domains

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#840]
### Description
We want to implement a new brand setting `allow_public_homepage` that controls how custom domains handle public access. This setting will determine whether users can create secret links directly from custom domains.

When enabled, the custom domain becomes the default domain for new secrets, allowing all users to create secrets directly. When disabled (default), the custom domain homepage displays only basic brand information without login or secret creation capabilities.

### Technical Considerations
- Custom domain validation needs to check `brand.allow_public_homepage` before allowing secret creation
- Default behavior (false) should maintain backward compatibility
- Need to ensure proper handling when loading custom domains via `OT::CustomDomain.load`

### TODO
- [x] Add `allow_public_homepage` boolean field to brand model
- [x] Update custom domain validation logic to check brand setting
- [x] Modify homepage controller to respect the setting
- [x] Update secret creation flow to handle custom domain as default when enabled
- [x] Add migration for new brand setting
- [ ] Update tests to cover both enabled/disabled scenarios

<details>
<summary>Implementation Context</summary>

This change primarily affects the secret concealment logic, specifically in how we handle custom domains during secret creation. The current implementation checks custom domain ownership, but needs to be extended to consider the new brand setting:

```ruby
@custom_domain = OT::CustomDomain.load(@share_domain, cust.custid)
```

This validation will need to be updated to accommodate the new public homepage behavior.
</details>

Related: #803 #765
