### ISSUE TITLE
Remove Array core extensions (legacy)

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#843]
### Description
We want to remove the core extensions to the Array class and refactor the statistical methods (mean, median, mode, etc.) into a dedicated module. This change will help prevent potential conflicts with other libraries and follow Ruby best practices for extending core classes.

### Technical Considerations
- Moving methods to a new module (e.g., `Statistics`) will require changes in all places where these Array methods are currently used
- Need to ensure backward compatibility or provide a clear migration path
- Consider implementing as refinements instead of global core extensions

### TODO
- [ ] Create new `Statistics` module
- [ ] Move existing statistical methods (sum, mean, median, etc.) to the new module
- [ ] Update all existing usages of these methods
- [ ] Add proper documentation for the new module
- [ ] Write tests for the new module implementation
- [x] Remove Array core extensions
- [ ] Add deprecation warnings if needed

<details>
<summary>Current Methods to Move</summary>

```ruby
- sum
- mean
- median
- histogram
- mode
- squares
- variance
- deviation (with sd alias)
- permute/permute!
- random
- percentile/percentile_index
```
</details>

### Potential Pitfalls
- Breaking changes in existing codebase
- Performance implications of using module methods vs. direct Array methods
- Possible naming conflicts with other statistical libraries
- Need to handle edge cases (empty arrays, non-numeric values) consistently
