### ISSUE TITLE
Review pre-commit hooks config for better performance

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#844]
We want to review and optimize our pre-commit hooks configuration to improve the development workflow speed. Currently, some developers have noted that the pre-commit checks are taking longer than necessary, especially for JSON validation.

### TODO
- [x] Review current pre-commit hooks configuration
- [x] Identify hooks that can be optimized or potentially removed
- [x] Evaluate if certain checks can be run only on changed files instead of all files
- [ ] Consider parallel execution options for compatible hooks

### Technical Considerations
- Need to balance between thorough validation and performance
- Consider caching mechanisms for repeated checks
- Evaluate if some checks can be moved to CI pipeline instead of pre-commit
- Look into JSON validation alternatives that handle duplicate keys more efficiently

<details>
<summary>Current Issues Example</summary>

```
pre-commit run --config .pre-push-config.yaml --all-files
Validate YAML files......................................................Passed
Validate TOML files......................................................Passed
Validate JSON files......................................................Failed
```

This shows that JSON validation in particular might need optimization, especially for handling locale files with potential duplicate keys.
</details>
