### ISSUE TITLE
Implement standardized database migration system with BaseMigration class

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#847]
### Description
We want to establish a consistent and reliable system for running database migrations in our application. The current migration scripts use direct Redis connections and lack standardization, making them harder to maintain and potentially risky to run in production.

### Technical Considerations
- Migrations need to use the same Redis connection method as the main application
- Must support both CLI execution and REPL console usage
- Should provide clear feedback and exit codes
- Must handle large datasets efficiently

### Implementation Details
<details>
<summary>Click to see the technical implementation</summary>

1. Created BaseMigration class to provide:
   - Standard interface via #migrate method
   - Redis connection management through Familia
   - Logging utilities
   - Class-level .run method

2. Migration script structure:
   ```ruby
   module Onetime
     class Migration < BaseMigration
       def migrate
         # Migration-specific logic
         true  # or false on failure
       end
     end
   end
   ```

3. Usage methods:
   ```bash
   # List available migrations
   bin/ots migrate
   
   # Run specific migration
   bin/ots migrate 816_populate_display_domains.rb
   ```
</details>

### TODO
- [ ] Add tests for BaseMigration class
- [ ] Document migration creation process in developer docs
- [ ] Consider adding migration generator script
- [ ] Add rollback support to migration interface
- [ ] Add dry-run option for migrations

### Potential Pitfalls
- Migrations need to handle partial failure states
- Large datasets require careful memory management
- Multiple deployment targets need consistent Redis configuration
- Migration scripts need to be idempotent

This ticket aligns with our goals of improving maintainability and reducing operational risk when performing database updates.
