### ISSUE TITLE
Implement Branded Homepage with Dual Experience Modes

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#878]
We want to create a dynamic homepage that can adapt between two primary modes: a lightweight landing page and an activated secrets page, both leveraging domain-specific branding and maintaining a clean, focused user experience.

### TODO Checklist
- [ ] Create base homepage component with mode-switching capability
- [ ] Develop landing page mode (readonly, minimal content)
- [ ] Develop secrets-enabled mode (simplified secret creation flow)
- [ ] Implement dynamic branding injection (logo, colors, fonts)
- [ ] Add responsive design considerations
- [ ] Create accessible navigation and interaction patterns

### Design Considerations
1. Landing Page Mode:
   - Minimal, informative content
   - Clear service explanation
   - Prominent branding elements
   - Single primary call-to-action

2. Secrets-Enabled Mode:
   - Simple secret creation interface
   - Branded color scheme
   - Streamlined user flow
   - Minimal external links/distractions

### Opportunities for Improvement
- Implement smooth transitions between modes
- Add subtle animations and micro-interactions
- Ensure consistent branding application
- Create reusable components for different sections

<details>
<summary>Proposed Component Structure</summary>

```typescript
interface HomepageProps {
  mode: 'landing' | 'secrets';
  brandSettings: BrandSettings;
}

// Potential component breakdown
<BrandedHomepage 
  :mode="currentMode"
  :brandSettings="domainBranding"
>
  <LandingPageContent />
  <SecretCreationFlow />
</BrandedHomepage>
```
</details>

### Technical Considerations
- Use Vue 3 Composition API
- Leverage dynamic component rendering
- Implement prop-based branding injection
- Create flexible routing logic

**Acceptance Criteria:**
- [ ] Landing page loads with minimal, branded content
- [ ] Secrets mode provides direct secret creation path
- [ ] Branding is consistently applied across modes
- [ ] Mobile and desktop experiences are equally refined
- [ ] Accessibility standards are maintained

**Related Files:** 
- `src/views/BrandedHomepage.vue` (new component)
- `src/components/homepage/LandingPageContent.vue`
- `src/components/homepage/SecretCreationFlow.vue`

**Design Token Considerations:**
- Dynamic color scheme adaptation
- Font family injection
- Logo placement and sizing
- Responsive layout scaling

**Priority:** High
**Complexity:** High
