### ISSUE TITLE
Implement Branded Homepage Mode Toggle Mechanism

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#879]
We want to develop a robust mechanism for managing and toggling between landing and secrets modes for branded homepages, providing administrators with granular control over domain-specific experiences.

### TODO Checklist
- [x] Design mode toggle configuration in domain settings
- [x] Create backend endpoint for mode management
- [x] Implement frontend mode switching logic
- [x] Add access control and permission checks
- [ ] Develop admin interface for mode configuration

### Technical Considerations
1. Mode Configuration Options:
   - Default mode (landing/secrets)
   - Ability to disable specific modes
   - Conditional mode activation based on domain settings

2. Potential Configuration Schema:
```typescript
interface DomainModeSettings {
  defaultMode: 'landing' | 'secrets';
  landingModeEnabled: boolean;
  secretsModeEnabled: boolean;
  requireAuthentication?: boolean;
  customRedirectUrl?: string;
}
```

### Potential Pitfalls
- Ensure secure mode switching
- Prevent unauthorized mode access
- Handle edge cases in mode transitions
- Maintain consistent user experience

<details>
<summary>Proposed Mode Switching Flow</summary>

```javascript
function determineDomainMode(domainSettings) {
  // Priority: 
  // 1. Explicit mode selection
  // 2. Default domain setting
  // 3. Fallback to landing mode
  if (domainSettings.currentMode) return domainSettings.currentMode;
  if (domainSettings.defaultMode) return domainSettings.defaultMode;
  return 'landing';
}
```
</details>

### Acceptance Criteria
- [x] Administrators can configure homepage mode
- [x] Mode switching respects domain-specific rules
- [x] Unauthorized mode access is prevented
- [ ] Smooth transition between modes
- [ ] Comprehensive logging of mode changes

**Related Files:**
- `src/views/BrandedHomepage.vue`
- `src/services/domainConfigService.ts`
- `src/types/domainSettings.ts`

### Design Considerations
1. Admin Interface Requirements:
   - Toggle switches for modes
   - Preview functionality
   - Clear mode description
   - Immediate preview of changes

2. User Experience:
   - Clear mode indicators
   - Graceful fallback mechanisms
   - Informative error states

**Security Considerations:**
- Implement role-based access control
- Add audit logging for mode changes
- Validate mode transitions server-side

**Priority:** High
**Complexity:** Moderate to High

**Additional Notes:**
- Develop comprehensive test cases
- Update custom domain documentation
- Consider internationalization of mode descriptions
- Implement feature flags for gradual rollout
