### ISSUE TITLE
Fix Type Errors and Component Prop Validations Across Frontend Components

### ISSUE THREAD

**Issue by delano** [onetimesecret/onetimesecret#906]
We want to address several TypeScript type errors and component prop validation issues across multiple Vue components. These issues are primarily related to type definitions, prop interfaces, and component interactions.

### Tasks
- [x] Fix `CustomDomain` type import in `DomainVerificationInfo.vue`
- [x] Resolve boolean type assignment in `DomainsTable.vue`
- [x] Correct prop type definitions for `DropdownToggle` in `LanguageToggle.vue`
- [x] Address API response type handling in `VerifyDomainDetails.vue`
- [x] Fix API token response type in `APIKeyForm.vue`
- [x] Correct prop types for `FancyIcon` in `HeaderUserNav.vue`
- [x] Update type definitions for secret metadata properties in `SecretMetadataTableItem.vue`

### Technical Considerations
1. Need to ensure proper type definitions are exported from `@/types/api/responses`
2. Consider implementing proper interface definitions for API responses
3. Review component prop definitions to ensure proper type safety
4. Evaluate the need for type guards where complex type assertions are being used

<details>
<summary>Detailed Issues Breakdown - Part 1</summary>

```typescript
// Type Definition Issues
1. Missing CustomDomain export
2. Boolean type assignment issues
3. Component prop interface mismatches
4. API response type safety
5. Date vs string type conflicts in metadata handling

// Component Fixes Needed
- Need to properly type API response handlers
- Review and update component prop interfaces
- Add proper type guards for nullable values
- Implement proper type checking for optional properties
```
</details>

<details>
<summary>Detailed Issues Breakdown - Part 2</summary>

### 1. Date Type Mismatches
- Multiple instances of `string | number` being assigned to `Date` type
- Need to transform date strings/numbers to Date objects consistently
- Affects: metadataStore, customerStore, domainsStore, secretsStore

### 2. Property Access Issues
- Unsafe access on nullable objects (cust.plan, result.record.key)
- Missing type definitions for properties like:
  - is_destroyed
  - is_received 
  - is_burned
  - has_passphrase
  - received_date
  - burned_date

### 3. Zod Schema Issues
- Invalid enum schema definitions using Object.values()
- Schema validation errors in domain/brand.ts
- Record response schema type mismatches

### 4. Component Prop Type Mismatches 
- Stripe types incomplete (Customer, Subscription)
- Cluster prop missing required fields
- Feedback prop missing required stamp field

### 5. API Response Type Issues
- Response.success property access error
- Details object shape mismatches
- Nullable fields not properly typed

## Relevant files
```
src/
├── utils/
│   └── dates.ts           # Date transformation utilities
├── types/
│   ├── api/
│   │   └── responses.ts   # API response interfaces
│   └── models/
│       ├── metadata.ts    # Metadata related types
│       └── customer.ts    # Customer related types
├── schemas/
│   └── models/
│       └── domain/
│           └── brand.ts   # Brand schema definitions
├── stores/
│   ├── metadataStore.ts   # Metadata store
│   ├── customerStore.ts   # Customer store
│   └── domainsStore.ts    # Domains store
└── components/
    └── secrets/
        ├── metadata/
        │   ├── MetadataDisplayCase.vue
        │   └── SecretLink.vue
        └── form/
            └── SecretContentInputArea.vue
```

</details>

### Potential Pitfalls
- Changes to type definitions might affect other components not currently showing errors
- API response type changes might require updates to backend documentation
- Component prop changes might break existing component usage patterns
- Need to maintain backward compatibility while fixing type issues
